# Generated by Django 5.0.2 on 2024-03-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3, verbose_name='Регион')),
                ('city', models.CharField(max_length=3, verbose_name='Город')),
                ('addr', models.CharField(max_length=4, verbose_name='Адрес')),
                ('full_address', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.PositiveIntegerField(default=0, verbose_name='Скорость')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('loc_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links_loc_1', to='rbuilder.locations')),
                ('loc_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links_loc_2', to='rbuilder.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.PositiveIntegerField(default=0, verbose_name='Скорость')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('loc_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_loc_1', to='rbuilder.locations', verbose_name='Локация 1')),
                ('loc_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_loc_2', to='rbuilder.locations', verbose_name='Локация 2')),
            ],
        ),
    ]
