# Generated by Django 5.0.2 on 2024-03-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='region',
            field=models.CharField(default='Europe', max_length=3, verbose_name='Регион'),
        ),
    ]
