# Generated by Django 5.0.2 on 2024-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbuilder', '0002_locations_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='region',
            field=models.CharField(max_length=20, verbose_name='Регион'),
        ),
    ]
