# Generated by Django 5.0.2 on 2024-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbuilder', '0003_alter_locations_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.CharField(max_length=3, verbose_name='Страна'),
        ),
    ]
